name: CI Create React App

on:
  pull_request:
    branches: [develop]

jobs:
  lint_pr:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
        #   Clean instal for Ci server
      - run: npm ci
      - run: npm lint
      - run: npm run build
